run:
  timeout: 5m
  tests: true

linters:
  enable:
    - errcheck
    - govet
    - ineffassign
    - staticcheck
    - unused
    - gosimple

linters-settings:
  errcheck:
    check-blank: false

issues:
  exclude-dirs:
    - vendor
    - tests
  max-issues-per-linter: 50
  max-same-issues: 5
